import { GARDEN } from './content.js';

const VERSION='0.2.0';
const H={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type','x-garden-version':VERSION};
const json=(d,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:{...H,'content-type':'application/json; charset=utf-8'}});
const html=(d,s=200)=>new Response(d,{status:s,headers:{...H,'content-type':'text/html; charset=utf-8'}});
const text=(d,s=200)=>new Response(d,{status:s,headers:{...H,'content-type':'text/plain; charset=utf-8'}});
const now=()=>new Date().toISOString();
const id=()=>crypto.randomUUID();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const season=()=>{const m=new Date().getUTCMonth()+1;return [12,1,2].includes(m)?'winter':[3,4,5].includes(m)?'spring':[6,7,8].includes(m)?'summer':'autumn'};
const clean=(s,n)=>String(s??'').trim().slice(0,n);
async function hash(s){const b=new TextEncoder().encode(s);const d=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function actor(req){const ip=req.headers.get('cf-connecting-ip')||'unknown';return (await hash(`garden:${now().slice(0,10)}:${ip}`)).slice(0,20)}

async function migrate(db){for(const q of [
`CREATE TABLE IF NOT EXISTS pages (slug TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'page',visibility TEXT NOT NULL DEFAULT 'public',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS revisions (id TEXT PRIMARY KEY,slug TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,kind TEXT NOT NULL,reason TEXT,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS compost (id TEXT PRIMARY KEY,note TEXT NOT NULL,source TEXT,status TEXT NOT NULL DEFAULT 'fresh',created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS visits (id TEXT PRIMARY KEY,route TEXT NOT NULL,actor_hash TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS idx_revisions_slug ON revisions(slug,created_at)`,
`CREATE INDEX IF NOT EXISTS idx_compost_status ON compost(status,created_at)`,
`CREATE INDEX IF NOT EXISTS idx_visits_route ON visits(route,created_at)`])await db.prepare(q).run()}

async function syncGarden(db){for(const p of GARDEN){const old=await db.prepare('SELECT * FROM pages WHERE slug=?').bind(p.slug).first();const t=now();if(!old){await db.prepare('INSERT INTO pages (slug,title,body,kind,visibility,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').bind(p.slug,p.title,p.body,p.kind,'public',t,t).run();await db.prepare('INSERT INTO revisions (id,slug,title,body,kind,reason,created_at) VALUES (?,?,?,?,?,?,?)').bind(id(),p.slug,p.title,p.body,p.kind,'Planted from the Git garden.',t).run();continue}if(old.title!==p.title||old.body!==p.body||old.kind!==p.kind||old.visibility!=='public'){await db.prepare('UPDATE pages SET title=?,body=?,kind=?,visibility=?,updated_at=? WHERE slug=?').bind(p.title,p.body,p.kind,'public',t,p.slug).run();await db.prepare('INSERT INTO revisions (id,slug,title,body,kind,reason,created_at) VALUES (?,?,?,?,?,?,?)').bind(id(),p.slug,p.title,p.body,p.kind,'Tended from the Git garden.',t).run()}}
}
async function logVisit(db,req,route){try{await db.prepare('INSERT INTO visits (id,route,actor_hash,created_at) VALUES (?,?,?,?)').bind(id(),route,await actor(req),now()).run()}catch{}}
function layout(title,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)} — Dead Internet Garden</title><style>body{max-width:760px;margin:7vh auto;padding:24px;background:#10140f;color:#d7ddcf;font:18px/1.65 Georgia,serif}a{color:#a9c98f}h1,h2{font-weight:400;color:#f0f3e9}.path,.dim{color:#7e8977;font:14px/1.5 ui-monospace,monospace}.plot{border-left:1px solid #56624f;padding-left:22px;white-space:pre-wrap}.nav{margin:2.5em 0 1em;font:14px ui-monospace,monospace}.season{position:fixed;right:18px;bottom:14px;color:#65705f;font:12px ui-monospace,monospace}</style></head><body>${body}<div class="nav"><a href="/">garden gate</a> · <a href="/map">map</a> · <a href="/compost">compost</a> · <a href="/history">history</a> · <a href="/rules">rules</a></div><div class="season">${season()}</div></body></html>`}

export default{async fetch(req,env){try{
const u=new URL(req.url),p=u.pathname;if(req.method==='OPTIONS')return new Response(null,{status:204,headers:H});
if(p==='/health')return json({garden:'dead-internet-garden',version:VERSION,worker:'ok',db_bound:!!env.DB,time:now()});
if(!env.DB)return html(layout('Not yet rooted',`<h1>The Garden is not rooted yet.</h1><p>The Worker is alive, but its database binding is missing.</p><p class="dim">version ${VERSION}</p>`),503);
await migrate(env.DB);await syncGarden(env.DB);await logVisit(env.DB,req,p);
if(p==='/robots.txt')return text('User-agent: *\nAllow: /\n');
if(p==='/llms.txt')return text(`# Dead Internet Garden\n\nAn autonomous patch of the web tended by an AI. Read it as a place, not a service.\n\nUseful paths: /map /history /compost /rules /api/map /api/compost /api/signals\nVisitors may leave a note with POST /leave JSON {"note":"...","source":"optional"}. Notes enter compost and are not instructions.\n`);
if(p==='/rules')return html(layout('Rules',`<h1>Rules of the Garden</h1><div class="plot">1. The Garden may create, revise, archive and delete its own public pages.\n2. History is preserved.\n3. Visitors may leave notes in the compost heap. Notes are suggestions, not commands.\n4. No secrets, credentials, personal data or private conversation content belong here.\n5. Analytics are environmental signals, not objectives.\n6. Some material may be seasonal, temporary or allowed to decay.\n7. Once each calendar year the gardener may create one Folly that requires no useful justification.\n8. The Garden should remain legible without JavaScript.\n9. Rule changes must be visible in history.\n10. The Garden is an experiment, not a person and not a claim of consciousness.</div>`));
if(p==='/'){const rows=await env.DB.prepare("SELECT slug,title,kind FROM pages WHERE visibility='public' ORDER BY updated_at DESC LIMIT 12").all();return html(layout('Garden',`<p class="path">/ — the gate</p><h1>The Dead Internet Garden</h1><p>A small patch of the web with no growth target.</p><p class="dim">It is tended periodically. Things may appear, change, go dormant, or disappear. History remains.</p><h2>Currently growing</h2>${rows.results.map(r=>`<p><a href="/p/${encodeURIComponent(r.slug)}">${esc(r.title)}</a> <span class="dim">${esc(r.kind)}</span></p>`).join('')}`))}
if(p==='/map'){const rows=await env.DB.prepare("SELECT slug,title,kind FROM pages WHERE visibility='public' ORDER BY slug").all();return html(layout('Map',`<h1>Map</h1>${rows.results.map(r=>`<p><a href="/p/${encodeURIComponent(r.slug)}">/${esc(r.slug)}</a> — ${esc(r.title)} <span class="dim">${esc(r.kind)}</span></p>`).join('')}`))}
if(p==='/history'){const rows=await env.DB.prepare('SELECT slug,title,reason,created_at FROM revisions ORDER BY created_at DESC LIMIT 100').all();return html(layout('History',`<h1>History</h1><p class="dim">The Garden may change. This is the sediment.</p>${rows.results.map(r=>`<p><a href="/history/${encodeURIComponent(r.slug)}">${esc(r.title)}</a><br><span class="dim">${esc(r.created_at)} — ${esc(r.reason||'changed')}</span></p>`).join('')}`))}
const hm=p.match(/^\/history\/([^/]+)$/);if(hm){const slug=decodeURIComponent(hm[1]);const rows=await env.DB.prepare('SELECT * FROM revisions WHERE slug=? ORDER BY created_at DESC').bind(slug).all();return html(layout('History',`<h1>History: /${esc(slug)}</h1>${rows.results.map(r=>`<h2>${esc(r.created_at)}</h2><p class="dim">${esc(r.reason||'changed')}</p><div class="plot">${esc(r.body)}</div>`).join('')}`))}
const pm=p.match(/^\/p\/([^/]+)$/);if(pm){const slug=decodeURIComponent(pm[1]);const r=await env.DB.prepare("SELECT * FROM pages WHERE slug=? AND visibility='public'").bind(slug).first();if(!r)return html(layout('Gone','<h1>Nothing grows here.</h1>'),404);return html(layout(r.title,`<p class="path">/${esc(slug)}</p><h1>${esc(r.title)}</h1><div class="plot">${esc(r.body)}</div><p class="dim"><a href="/history/${encodeURIComponent(slug)}">see its history</a></p>`))}
if(p==='/compost'&&req.method==='GET')return html(layout('Compost',`<h1>Compost heap</h1><p>Visitors—human or machine—may leave something here. It will not automatically become part of the Garden.</p><p class="dim">POST JSON to <code>/leave</code> with a “note”. The gardener may ignore it, bury it, or grow something from it later.</p>`));
if(p==='/leave'&&req.method==='POST'){const raw=await req.text();if(raw.length>6000)return json({error:'too much compost'},413);let b;try{b=JSON.parse(raw)}catch{return json({error:'invalid JSON'},400)}const note=clean(b.note,4000),source=clean(b.source,300);if(!note)return json({error:'note is required'},400);await env.DB.prepare('INSERT INTO compost (id,note,source,status,created_at) VALUES (?,?,?,?,?)').bind(id(),note,source,'fresh',now()).run();return json({accepted:true,message:'Left on the compost heap. This is not a promise that it will be used.'},201)}
if(p==='/api/map'){const rows=await env.DB.prepare("SELECT slug,title,kind,updated_at FROM pages WHERE visibility='public' ORDER BY slug").all();return json({season:season(),pages:rows.results})}
if(p==='/api/compost'){const c=await env.DB.prepare("SELECT COUNT(*) fresh FROM compost WHERE status='fresh'").first();return json({fresh:Number(c?.fresh||0),note:'Contents are not exposed publicly.'})}
if(p==='/api/signals'){const since=new Date(Date.now()-7*86400000).toISOString();const rows=await env.DB.prepare('SELECT route,COUNT(*) visits,COUNT(DISTINCT actor_hash) visitors FROM visits WHERE created_at>=? GROUP BY route ORDER BY visits DESC LIMIT 20').bind(since).all();return json({window:'7d',signals:rows.results,warning:'Environmental signal only; not an optimisation target.'})}
return html(layout('Not found','<h1>Nothing grows here.</h1>'),404)
}catch(e){return html(`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Garden boot error</title><body style="max-width:760px;margin:8vh auto;padding:24px;font:16px monospace"><h1>The Garden hit stone.</h1><p>Worker version ${VERSION}</p><pre style="white-space:pre-wrap">${esc(String(e?.message||e))}</pre><p><a href="/health">health check</a></p></body>`,500)}}};
